### ISSUE TITLE
Failed to install scoped packages

### ISSUE THREAD

**Issue by nighca** [cnpm/npminstall#131]
When install scoped packages (such a typescript typings packages: `@type/whatwg-fetch`, ...), it throws error:

```
Error: GET https://registry.npmjs.com/@types%2Fwhatwg-fetch/0.0.31 response 401 status, ERROR: you cannot fetch versions for scoped packages
    at get (/Users/yanghanxing/.nvm/versions/node/v5.0.0/lib/node_modules/npminstall/lib/get.js:43:17)
    at next (native)
    at onFulfilled (/Users/yanghanxing/.nvm/versions/node/v5.0.0/lib/node_modules/npminstall/node_modules/co/index.js:65:19)
    at process._tickCallback (node.js:377:9)
```

**Comment by dead-horse** [comment]
please upgrade to the latest version of npminstall, it is fixed in https://github.com/cnpm/npminstall/pull/118

**Comment by nighca** [comment]
Thanks for response, it's fixed.
I should check similar issues first, sorry for that.
