### ISSUE TITLE
`cnpm install` 报错

### ISSUE THREAD

**Issue by wuyuanwei** [cnpm/npminstall#151]
```
% cnpm install
⠇ Installing lodash.isempty@^3.0.4Error: Hostname/IP doesn't match certificate's altnames: "Host: cdn.npm.taobao.org. is not in the cert's altnames: DNS:*.oss-cn-hangzhou.aliyuncs.com, DNS:oss-cn-hangzhou.aliyuncs.com"
    at Object.checkServerIdentity (tls.js:186:15)
    at TLSSocket.<anonymous> (_tls_wrap.js:1028:29)
    at emitNone (events.js:67:13)
    at TLSSocket.emit (events.js:166:7)
    at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._finishInit (_tls_wrap.js:586:8)
    at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onhandshakedone (_tls_wrap.js:428:38)
npminstall version: 2.9.4
npminstall args: /my/path/node/bin/node /my/path/node/lib/node_modules/cnpm/node_modules/.bin/npminstall --china --userconfig=~/.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://registry.npm.taobao.org
```

**Comment by dead-horse** [comment]
证书有点问题，现在应该已经修复了
