### ISSUE TITLE
electron-react-boilerplate install fail

### ISSUE THREAD

**Issue by afc163** [cnpm/npminstall#257]
https://github.com/chentsulin/electron-react-boilerplate

```
Unhandled rejection Error: Invalid package name "_fsevents": name cannot start with an underscore
    at invalidPackageName (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:71:15)
    at Result.setName (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:107:11)
    at new Result (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:96:23)
    at resolve (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:45:15)
    at npa (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:39:10)
    at /usr/local/lib/node_modules/npm/lib/ls.js:65:17
    at Array.map (<anonymous>)
    at ls.fromTree (/usr/local/lib/node_modules/npm/lib/ls.js:61:17)
    at /usr/local/lib/node_modules/npm/lib/ls.js:42:7
    at /usr/local/lib/node_modules/npm/lib/install/read-shrinkwrap.js:55:14
    at /usr/local/lib/node_modules/npm/node_modules/iferr/index.js:13:50
    at BB.join.then (/usr/local/lib/node_modules/npm/lib/install/read-shrinkwrap.js:41:16)
    at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
npm ERR! cb() never called!
```

**Comment by fengmk2** [comment]
_fsevents 模块名称太奇怪了。

**Comment by fengmk2** [comment]
它的 postinstall 执行了一个检查。。。

```
node -r babel-register internals/scripts/CheckNativeDep.js
npm ls _fsevents@1.1.3@fsevents _node-sass@4.7.2@node-sass fsevents node-sass --json
```

**Comment by fengmk2** [comment]
目前这个报错不影响安装，只是没有做 native 检查
