### ISSUE TITLE
cnpm install出错了~

### ISSUE THREAD

**Issue by AnoLu** [cnpm/npminstall#365]
✖ Install fail! TypeError: Cannot read property 'https' of undefined
TypeError: Cannot read property 'https' of undefined
    at module.exports (/var/lib/jenkins/.nvm/versions/node/v10.13.0/lib/node_modules/cnpm/node_modules/npminstall/lib/download/git.js:19:22)
    at module.exports (/var/lib/jenkins/.nvm/versions/node/v10.13.0/lib/node_modules/cnpm/node_modules/npminstall/lib/download/index.js:17:18)
    at _install (/var/lib/jenkins/.nvm/versions/node/v10.13.0/lib/node_modules/cnpm/node_modules/npminstall/lib/install.js:125:22)
    at install (/var/lib/jenkins/.nvm/versions/node/v10.13.0/lib/node_modules/cnpm/node_modules/npminstall/lib/install.js:26:18)
    at installOne (/var/lib/jenkins/.nvm/versions/node/v10.13.0/lib/node_modules/cnpm/node_modules/npminstall/lib/local_install.js:209:21)
npminstall version: 5.1.2
npminstall args: /var/lib/jenkins/.nvm/versions/node/v10.13.0/bin/node

请问这是不支持还是一个bug?我的包地址是：
`git+https://token@gitlab`

**Comment by gemwuu** [comment]
#370 fix this.
