### ISSUE TITLE
[Bug] npminstall<latest> cannot be used with 14.17.3 node

### ISSUE THREAD

**Issue by fengyon** [cnpm/npminstall#468]
npminstall<latest> cannot be used with 14.17.3 node, but the lowest version of node is 14.x as the `readme.md` tell me

node version

```
nvm use 14.17.3
```

```
npm install npminstall -g
```

```
npminstall -v
```

the error message is
```
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'node:util'
Require stack:
- C:\Users\xxx\AppData\Roaming\npm\node_modules\npminstall\bin\install.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (C:\Users\xxx\AppData\Roaming\npm\node_modules\npminstall\bin\install.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\xxx\\AppData\\Roaming\\npm\\node_modules\\npminstall\\bin\\install.js'
  ]
}

```

**Comment by fengmk2** [comment]
require node >= 14.18.0

https://github.com/cnpm/npminstall/blob/master/package.json

**Comment by fengyon** [comment]
but some dependencies of `npminstall` is not supported by 14.8.0 node from the message of installation of `npminstall`

that is:  
```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'urllib@3.19.3',
npm WARN EBADENGINE   required: { node: '>= 14.19.3' },
npm WARN EBADENGINE   current: { node: 'v14.17.3', npm: '8.19.4' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'type-fest@4.7.1',
npm WARN EBADENGINE   required: { node: '>=16' },
npm WARN EBADENGINE   current: { node: 'v14.17.3', npm: '8.19.4' }
npm WARN EBADENGINE }
```

**Comment by fengmk2** [comment]
you should use the latest v14 version
maybe use the v18 is better, Node.js has no more maintainer `Node.js < 18`
